DROP TABLE callrecordmaster;
CREATE TABLE callrecordmaster(
        CallID varchar(100)     PRIMARY KEY,
        CustomerID varchar(15) NOT NULL,
        CallType smallint,
        CallDateTime timestamp NOT NULL,
        Duration integer NOT NULL,
	BilledDuration integer NOT NULL,
        Direction char(1),
        SourceIP varchar(15),
        OriginatingNumber varchar(50) NOT NULL,
        DestinationNumber varchar(50) NOT NULL,
        LRN      varchar(50),
	LRNDipFee numeric(9,9) NOT NULL DEFAULT 0,
	BilledNumber varchar(50) NOT NULL,
	BilledPrefix varchar(10),
	RatedDateTime timestamp NOT NULL,
	RetailRate numeric(9,7) NOT NULL,		
        CNAMDipped boolean,
	CNAMFee numeric (9,9) NOT NULL DEFAULT 0,
	BilledTier smallint,
	RateCenter varchar(50),
	BillingBatchID Varchar(15),
	RetailPrice numeric(19,7) NOT NULL,
	CarrierID varchar(100),
	WholesaleRate numeric(19, 7),
	WholesalePrice numeric(19, 7),	
        RoutingPrefix varchar(10),
        CanBeFree boolean,	
        RowID serial4 UNIQUE NOT NULL
);